// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Menu struct {
	ID       string      `json:"id"`
	MeuItems []*MenuItem `json:"meuItems"`
}

type MenuItem struct {
	ID      string `json:"id"`
	Menu    *Menu  `json:"menu"`
	Name    string `json:"name"`
	Keyword string `json:"keyword"`
}

type Restaurant struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Addr1   string  `json:"addr1"`
	Addr2   *string `json:"addr2"`
	City    string  `json:"city"`
	State   string  `json:"state"`
	Country string  `json:"country"`
	Zip     string  `json:"zip"`
	IsLive  bool    `json:"isLive"`
	Menu    *Menu   `json:"menu"`
}

func (Restaurant) IsEntity() {}
