// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MenuItem struct {
	ID           string      `json:"id"`
	Restaurant   *Restaurant `json:"restaurant"`
	Name         string      `json:"name"`
	Keyword      string      `json:"keyword"`
	PriceInCents int         `json:"priceInCents"`
}

func (MenuItem) IsEntity() {}

type Restaurant struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	Addr1    string      `json:"addr1"`
	Addr2    *string     `json:"addr2"`
	City     string      `json:"city"`
	State    string      `json:"state"`
	Country  string      `json:"country"`
	Zip      string      `json:"zip"`
	IsLive   bool        `json:"isLive"`
	MeuItems []*MenuItem `json:"meuItems"`
}

func (Restaurant) IsEntity() {}
